// Generated by CoffeeScript 1.12.2
(function() {
  var DomView, View,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  View = require('./view').View;

  DomView = (function(superClass) {
    extend(DomView, superClass);

    function DomView(subject, options1) {
      this.subject = subject;
      this.options = options1 != null ? options1 : {};
      DomView.__super__.constructor.call(this, this.subject, this.options);
    }

    DomView.prototype.markup = function() {
      var node;
      return ((function() {
        var i, len, ref, results;
        ref = this.artifact();
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          node = ref[i];
          results.push(node.outerHTML);
        }
        return results;
      }).call(this)).join('');
    };

    DomView.prototype._render = function() {
      var dom;
      dom = this.dom();
      this._bindings = this.preboundTemplate(dom, this.pointer());
      return dom;
    };

    DomView.prototype.wireEvents = function() {
      var binding, dom, i, len, ref;
      if (this._wired === true) {
        return;
      }
      this._wired = true;
      dom = this.artifact();
      if (typeof dom.data === "function") {
        dom.data('view', this);
      }
      this._wireEvents();
      if (this._bindings != null) {
        ref = this._bindings;
        for (i = 0, len = ref.length; i < len; i++) {
          binding = ref[i];
          if (binding.start != null) {
            binding.start();
          }
        }
        this._subwires = (function() {
          var j, len1, ref1, results;
          ref1 = this._bindings;
          results = [];
          for (j = 0, len1 = ref1.length; j < len1; j++) {
            binding = ref1[j];
            if (binding.view != null) {
              results.push(binding.view.react(function(view) {
                return view != null ? view.wireEvents() : void 0;
              }));
            }
          }
          return results;
        }).call(this);
      }
      return null;
    };

    DomView.prototype._destroy = function() {
      var base, binding, i, j, len, len1, ref, ref1, ref2, ref3, subwire;
      if (this._artifact != null) {
        ref = this._bindings;
        for (i = 0, len = ref.length; i < len; i++) {
          binding = ref[i];
          if ((ref1 = binding.view) != null) {
            if ((ref2 = ref1.get()) != null) {
              ref2.destroy();
            }
          }
          binding.stop();
        }
        if (this._subwires != null) {
          ref3 = this._subwires;
          for (j = 0, len1 = ref3.length; j < len1; j++) {
            subwire = ref3[j];
            subwire.stop();
          }
        }
        if (typeof (base = this._artifact).trigger === "function") {
          base.trigger('destroying');
        }
        return this._artifact.remove();
      }
    };

    DomView.build = function(fragment, template, options) {
      if (options == null) {
        options = {};
      }
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.prototype.dom = function() {
          return fragment.clone();
        };

        _Class.prototype.preboundTemplate = template(fragment);

        _Class.viewModelClass = options.viewModelClass;

        _Class.prototype._wireEvents = function() {
          return typeof options.wireEvents === "function" ? options.wireEvents(this.artifact(), this.subject, this) : void 0;
        };

        return _Class;

      })(DomView);
    };

    return DomView;

  })(View);

  module.exports = {
    DomView: DomView
  };

}).call(this);
