// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, List, ListView, Varying, from, identity, insertNode, mutators, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('janus'), Varying = ref.Varying, DomView = ref.DomView, mutators = ref.mutators, from = ref.from, List = ref.List;

  identity = require('janus').util.identity;

  $ = require('../util/dollar');

  ListView = (function(superClass) {
    extend(ListView, superClass);

    function ListView() {
      return ListView.__super__.constructor.apply(this, arguments);
    }

    ListView.prototype.dom = function() {
      return $('<ul class="janus-list"/>');
    };

    ListView.prototype.itemDom = function() {
      return $('<li/>');
    };

    ListView.prototype._initialize = function() {
      var base;
      this._point = this.pointer();
      return (base = this.options).renderItem != null ? base.renderItem : base.renderItem = identity;
    };

    ListView.prototype._render = function() {
      var binding, dom, i, idx, len, ref1;
      dom = this.dom();
      this._mappedBindings = this.subject.map((function(_this) {
        return function(item) {
          return _this._bindingForItem(item, _this.itemDom());
        };
      })(this));
      this._hookBindings(dom, this._mappedBindings);
      ref1 = this._mappedBindings.list;
      for (idx = i = 0, len = ref1.length; i < len; idx = ++i) {
        binding = ref1[idx];
        insertNode(dom, binding.dom, idx);
      }
      return dom;
    };

    ListView.prototype.attach = function(dom) {
      var bindings, initial, point;
      this._artifact = dom;
      point = this.pointer();
      bindings = dom.children().map((function(_this) {
        return function(idx, node) {
          return _this._bindingForItem(_this.subject.list[idx], $(node), false);
        };
      })(this)).get();
      initial = true;
      this._mappedBindings = this.subject.map((function(_this) {
        return function(item) {
          if (initial === true) {
            return bindings.shift();
          } else {
            return _this._bindingForItem(item, _this.itemDom());
          }
        };
      })(this));
      initial = false;
      this._hookBindings(dom, this._mappedBindings);
    };

    ListView.prototype._hookBindings = function(dom, bindings) {
      this.listenTo(bindings, 'added', (function(_this) {
        return function(binding, idx) {
          var ref1;
          insertNode(dom, binding.dom, idx);
          if (_this._wired === true) {
            return (ref1 = binding.view.get()) != null ? ref1.wireEvents() : void 0;
          }
        };
      })(this));
      return this.listenTo(bindings, 'removed', function(binding) {
        var ref1;
        if ((ref1 = binding.view.get()) != null) {
          ref1.destroy();
        }
        binding.stop();
        return binding.dom.remove();
      });
    };

    ListView.prototype._bindingForItem = function(item, node, immediate) {
      var binding, mutator;
      if (immediate == null) {
        immediate = true;
      }
      mutator = mutators.render(from.varying(Varying.of(item)));
      binding = this.options.renderItem(mutator)(node, this._point, immediate);
      binding.dom = node;
      return binding;
    };

    ListView.prototype.wireEvents = function() {
      var binding, i, len, ref1, ref2;
      if (this._wired === true) {
        return;
      }
      ListView.__super__.wireEvents.call(this);
      ref1 = this._mappedBindings.list;
      for (i = 0, len = ref1.length; i < len; i++) {
        binding = ref1[i];
        if ((ref2 = binding.view.get()) != null) {
          ref2.wireEvents();
        }
      }
      this._wireObservations = this._mappedBindings.map((function(_this) {
        return function(binding) {
          return _this.reactTo(binding.view, false, function(view) {
            return view.wireEvents();
          });
        };
      })(this));
      this.listenTo(this._wireObservations, 'removed', function(obs) {
        return obs.stop();
      });
    };

    ListView.prototype.__destroy = function() {
      var ref1;
      if (this._mappedBindings != null) {
        this._bindings = this._mappedBindings.list.slice();
        ListView.__super__.__destroy.call(this);
        this._mappedBindings.destroy();
      }
      return (ref1 = this._wireObservations) != null ? ref1.destroy() : void 0;
    };

    return ListView;

  })(DomView);

  insertNode = function(dom, itemDom, idx) {
    var children;
    children = dom.children();
    if (idx === 0) {
      return dom.prepend(itemDom);
    } else if (idx === children.length) {
      return dom.append(itemDom);
    } else {
      return children.eq(idx).before(itemDom);
    }
  };

  module.exports = {
    ListView: ListView,
    registerWith: function(library) {
      return library.register(List, ListView);
    }
  };

}).call(this);
