// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, LiteralView, find, from, ref, template;

  ref = require('janus'), DomView = ref.DomView, template = ref.template, find = ref.find, from = ref.from;

  $ = require('../util/dollar');

  LiteralView = DomView.build($('<span class="janus-literal"/>'), template(find('span').text(from(function(subject) {
    return subject;
  }))));

  module.exports = {
    LiteralView: LiteralView,
    registerWith: function(library) {
      library.register(String, LiteralView);
      library.register(Number, LiteralView);
      return library.register(Boolean, LiteralView);
    }
  };

}).call(this);
