// Generated by CoffeeScript 1.12.2
(function() {
  var Varying, from, getView, getView_subject, getView_subjectContext, getView_subjectCriteria, pointify, render;

  Varying = require('../core/varying').Varying;

  from = require('../core/from');

  pointify = function(x, point) {
    var ref, ref1;
    return (ref = x != null ? (ref1 = x.all) != null ? typeof ref1.point === "function" ? ref1.point(point) : void 0 : void 0 : void 0) != null ? ref : Varying.of(x);
  };

  getView = Varying.lift(function(subject, app, context, criteria, options) {
    return app.view(subject, Object.assign({
      context: context
    }, criteria), options);
  });

  getView_subject = Varying.lift(function(subject, app) {
    return app.view(subject);
  });

  getView_subjectContext = Varying.lift(function(subject, app, context) {
    return app.view(subject, {
      context: context
    });
  });

  getView_subjectCriteria = Varying.lift(function(subject, app, criteria) {
    return app.view(subject, criteria);
  });

  render = function(data, args) {
    var result;
    if (args == null) {
      args = {};
    }
    result = function(dom, point, immediate) {
      var view;
      if (immediate == null) {
        immediate = true;
      }
      view = (args.context == null) && (args.criteria == null) && (args.options == null) ? getView_subject(data.all.point(point), from.app().all.point(point)) : (args.criteria == null) && (args.options == null) ? getView_subjectContext(data.all.point(point), from.app().all.point(point), pointify(args.context, point)) : (args.context == null) && (args.options == null) ? getView_subjectCriteria(data.all.point(point), from.app().all.point(point), pointify(args.criteria, point)) : getView(data.all.point(point), from.app().all.point(point), pointify(args.context, point), pointify(args.criteria, point), pointify(args.options, point));
      return view.react(true, function(view_) {
        var children, ref, runBefore;
        runBefore = this.view != null;
        if (this.view == null) {
          this.view = new Varying();
        }
        if ((ref = this.view.get()) != null) {
          ref.destroy();
        }
        children = dom.children();
        if ((immediate === false) && (runBefore === false) && (children.length > 0)) {
          if (view_ != null) {
            view_.attach(children);
          }
        } else {
          dom.empty();
          if (view_ != null) {
            dom.append(view_.artifact());
          }
        }
        return this.view.set(view_);
      });
    };
    result.context = function(context) {
      return render(data, Object.assign({}, args, {
        context: context
      }));
    };
    result.criteria = function(criteria) {
      return render(data, Object.assign({}, args, {
        criteria: criteria
      }));
    };
    result.options = function(options) {
      return render(data, Object.assign({}, args, {
        options: options
      }));
    };
    return result;
  };

  module.exports = render;

}).call(this);
