// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, SuccessResultView, find, from, ref, template, types;

  ref = require('janus'), DomView = ref.DomView, template = ref.template, find = ref.find, from = ref.from, types = ref.types;

  $ = require('janus-dollar');

  SuccessResultView = DomView.build($('<div class="janus-successResult"/>'), template(find('div').render(from.self().map(function(view) {
    return view.subject.value;
  }))));

  module.exports = {
    SuccessResultView: SuccessResultView,
    registerWith: function(library) {
      return library.register(types.result.success, SuccessResultView);
    }
  };

}).call(this);
