// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, Varying, VaryingView, find, from, ref, template;

  ref = require('janus'), Varying = ref.Varying, DomView = ref.DomView, template = ref.template, find = ref.find, from = ref.from;

  $ = require('../util/dollar');

  VaryingView = DomView.build($('<div class="janus-varying"/>'), template(find('div').render(from(function(subject) {
    return subject;
  })).context(from.self(function(view) {
    var ref1;
    return (ref1 = view.options.libraryContext) != null ? ref1 : 'default';
  }))));

  module.exports = {
    VaryingView: VaryingView,
    registerWith: function(library) {
      return library.register(Varying, VaryingView);
    }
  };

}).call(this);
