// Generated by CoffeeScript 1.12.2
(function() {
  var cache, dollar;

  dollar = require('./dollar');

  cache = null;

  module.exports = function($) {
    dollar.set($);
    return cache != null ? cache : cache = {
      list: require('./list'),
      listEdit: require('./list-edit'),
      literal: require('./literal'),
      varying: require('./varying'),
      textAttribute: require('./text-attribute'),
      booleanAttribute: require('./boolean-attribute'),
      numberAttribute: require('./number-attribute'),
      enumAttribute: require('./enum-attribute'),
      enumAttributeList: require('./enum-attribute-list'),
      types: require('./types'),
      registerWith: function(library) {
        var _, ref, view;
        ref = this;
        for (_ in ref) {
          view = ref[_];
          if (view !== this.registerWith) {
            view.registerWith(library);
          }
        }
      }
    };
  };

}).call(this);
