// Generated by CoffeeScript 1.12.2
(function() {
  var Base, Library, match, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  util = require('../util/util');

  Base = require('../core/base').Base;

  Library = (function(superClass) {
    extend(Library, superClass);

    Library.prototype.isLibrary = true;

    Library.prototype._defaultContext = 'default';

    function Library(options1) {
      var base;
      this.options = options1 != null ? options1 : {};
      Library.__super__.constructor.call(this);
      this.bookcase = {};
      if ((base = this.options).handler == null) {
        base.handler = function(obj, book, options) {
          return new book(obj, util.extendNew(options.options, {
            libraryContext: options.context
          }));
        };
      }
    }

    Library.prototype.register = function(klass, book, options) {
      var base, bookId, classShelf, contextShelf, name, ref;
      if (options == null) {
        options = {};
      }
      bookId = Library._classId(klass);
      classShelf = (base = this.bookcase)[bookId] != null ? base[bookId] : base[bookId] = {};
      contextShelf = classShelf[name = (ref = options.context) != null ? ref : 'default'] != null ? classShelf[name] : classShelf[name] = [];
      contextShelf.push({
        book: book,
        options: options
      });
      if (options.priority != null) {
        contextShelf.sort(function(a, b) {
          var ref1, ref2;
          return ((ref1 = b.options.priority) != null ? ref1 : 0) - ((ref2 = a.options.priority) != null ? ref2 : 0);
        });
      }
      return book;
    };

    Library.prototype.get = function(obj, options) {
      var book, ref, ref1, ref2, result;
      if (options == null) {
        options = {};
      }
      if (options.debug === true) {
        debugger;
      }
      book = (ref = this._get(obj, obj != null ? obj.constructor : void 0, (ref1 = options.context) != null ? ref1 : this._defaultContext, options)) != null ? ref : this._get(obj, obj != null ? obj.constructor : void 0, 'default', options);
      if (book != null) {
        result = ((ref2 = options.handler) != null ? ref2 : this.options.handler)(obj, book, options);
        this.emit('got', result, obj, book, options);
      } else {
        this.emit('missed', obj, options);
      }
      return result != null ? result : null;
    };

    Library.prototype._get = function(obj, klass, context, options) {
      var bookId, contextShelf, i, len, record, ref;
      bookId = obj == null ? 'null' : obj["case"] != null ? "case@" + obj["case"].namespace + "." + obj.type : obj.isCase === true ? "case@" + obj.namespace + "." + obj.type : util.isNumber(obj) ? 'number' : util.isString(obj) ? 'string' : obj === true || obj === false ? 'boolean' : Library._classId(klass);
      contextShelf = (ref = this.bookcase[bookId]) != null ? ref[context] : void 0;
      if (contextShelf != null) {
        for (i = 0, len = contextShelf.length; i < len; i++) {
          record = contextShelf[i];
          if (match(obj, record, options.attributes)) {
            return record.book;
          }
        }
      }
      if ((klass != null) && (util.superClass(klass) != null)) {
        return this._get(obj, util.superClass(klass), context, options);
      }
    };

    Library.classKey = "__janus_classId" + (new Date().getTime());

    Library.classMap = {};

    Library._classId = function(klass) {
      var id;
      if (klass == null) {
        return 'null';
      } else if (klass["case"] != null) {
        return "case@" + klass["case"].namespace + "." + klass.type;
      } else if (klass.isCase === true) {
        return "case@" + klass.namespace + "." + klass.type;
      } else if (klass === Number) {
        return 'number';
      } else if (klass === String) {
        return 'string';
      } else if (klass === Boolean) {
        return 'boolean';
      } else {
        id = klass[this.classKey];
        if ((id != null) && this.classMap[id] === klass) {
          return klass[this.classKey];
        } else {
          id = util.uniqueId();
          this.classMap[id] = klass;
          return klass[this.classKey] = id;
        }
      }
    };

    return Library;

  })(Base);

  match = function(obj, record, attributes) {
    var base, isMatch;
    if ((typeof (base = record.options).rejector === "function" ? base.rejector(obj) : void 0) === true) {
      return false;
    }
    if ((record.options.acceptor != null) && (record.options.acceptor(obj) !== true)) {
      return false;
    }
    isMatch = true;
    if (attributes) {
      util.traverse(attributes, function(subpath, value) {
        if (util.deepGet(record.options.attributes, subpath) !== value) {
          return isMatch = false;
        }
      });
    }
    return isMatch;
  };

  module.exports = {
    Library: Library
  };

}).call(this);
