// Generated by CoffeeScript 1.12.2
(function() {
  var Map, Model, Null, Varying, cases, match, otherwise, ref, ref1, types, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  cases = require('../core/types').from;

  ref = require('../core/case'), match = ref.match, otherwise = ref.otherwise;

  types = require('../core/types');

  ref1 = require('../collection/map'), Null = ref1.Null, Map = ref1.Map;

  Varying = require('../core/varying').Varying;

  util = require('../util/util');

  Model = (function(superClass) {
    extend(Model, superClass);

    Model.prototype.isModel = true;

    function Model(data, options) {
      if (data == null) {
        data = {};
      }
      this._attributes = {};
      Model.__super__.constructor.call(this, data, options);
      this._bind();
    }

    Model.prototype.get = function(key) {
      var attribute, value;
      value = Model.__super__.get.call(this, key);
      if ((value == null) && ((attribute = this.attribute(key)) != null)) {
        value = attribute["default"]();
        if ((attribute.writeDefault === true) && (value !== void 0)) {
          this.set(key, value);
        }
      }
      return value != null ? value : null;
    };

    Model.prototype.attribute = function(key) {
      var base, base1;
      return (base = this._attributes)[key] != null ? base[key] : base[key] = typeof (base1 = this.constructor.schema.attributes[key]) === "function" ? new base1(this, key) : void 0;
    };

    Model.prototype.autoResolveWith = function(app) {
      var attribute, key;
      for (key in this.constructor.schema.attributes) {
        attribute = this.attribute(key);
        if (attribute.isReference === true && attribute.autoResolve === true) {
          attribute.resolveWith(app);
        }
      }
    };

    Model.prototype._bind = function() {
      var binding, key, ref2;
      this._bindings = {};
      ref2 = this.constructor.schema.bindings;
      for (key in ref2) {
        binding = ref2[key];
        this._bindings[key] = this.reactTo(binding.all.point(this.pointer()), this.set(key));
      }
    };

    Model.prototype.pointer = function() {
      return this.pointer$ != null ? this.pointer$ : this.pointer$ = match(cases.dynamic((function(_this) {
        return function(x) {
          if (util.isFunction(x)) {
            return Varying.of(x(_this));
          } else if (util.isString(x)) {
            return _this.watch(x);
          } else {
            return Varying.of(x);
          }
        };
      })(this)), cases.watch((function(_this) {
        return function(x) {
          return _this.watch(x);
        };
      })(this)), cases.attribute((function(_this) {
        return function(x) {
          return new Varying(_this.attribute(x));
        };
      })(this)), cases.varying((function(_this) {
        return function(x) {
          if (util.isFunction(x)) {
            return Varying.of(x(_this));
          } else {
            return Varying.of(x);
          }
        };
      })(this)), cases.app((function(_this) {
        return function(x) {
          var app;
          if ((app = _this.options.app) != null) {
            if (x != null) {
              return app.watch(x);
            } else {
              return new Varying(app);
            }
          } else {
            return cases.app();
          }
        };
      })(this)), cases.self((function(_this) {
        return function(x) {
          if (util.isFunction(x)) {
            return Varying.of(x(_this));
          } else {
            return Varying.of(_this);
          }
        };
      })(this)));
    };

    Model.prototype.validations = function() {
      return this._validations$ != null ? this._validations$ : this._validations$ = (function(_this) {
        return function() {
          var List, result;
          List = require('../collection/list').List;
          result = new List(_this.constructor.schema.validations).flatMap(function(binding) {
            return binding.all.point(_this.pointer());
          });
          result.destroyWith(_this);
          return result;
        };
      })(this)();
    };

    Model.prototype.issues = function() {
      return this._issues$ != null ? this._issues$ : this._issues$ = this.validations().filter(types.validity.invalid.match).map(function(invalid) {
        return invalid.get();
      });
    };

    Model.prototype.valid = function() {
      return this._valid$ != null ? this._valid$ : this._valid$ = this.issues().watchLength().map(function(length) {
        return length === 0;
      });
    };

    Model.prototype._parentChanged = function(key, newValue, oldValue) {
      if (this._bindings[key] == null) {
        return Model.__super__._parentChanged.call(this, key, newValue, oldValue);
      }
    };

    Model.prototype.__destroy = function() {
      var _, attribute, ref2;
      ref2 = this._attributes;
      for (_ in ref2) {
        attribute = ref2[_];
        if (attribute != null) {
          attribute.destroy();
        }
      }
    };

    Model.schema = {
      attributes: {},
      bindings: {},
      validations: []
    };

    Model.deserialize = function(data) {
      var attribute, key, prop, ref2;
      ref2 = this.schema.attributes;
      for (key in ref2) {
        attribute = ref2[key];
        prop = util.deepGet(data, key);
        if (prop != null) {
          util.deepSet(data, key)(attribute.deserialize(prop));
        }
      }
      return new this(data);
    };

    Model.build = function() {
      var i, len, part, parts, schema;
      parts = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      schema = {
        attributes: Object.assign({}, this.schema.attributes),
        bindings: Object.assign({}, this.schema.bindings),
        validations: this.schema.validations.slice()
      };
      for (i = 0, len = parts.length; i < len; i++) {
        part = parts[i];
        part(schema);
      }
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.schema = schema;

        return _Class;

      })(this);
    };

    return Model;

  })(Map);

  module.exports = {
    Model: Model
  };

}).call(this);
