// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    view: {
      list: require('./view/list'),
      listEdit: require('./view/list-edit'),
      literal: require('./view/literal'),
      varying: require('./view/varying'),
      textAttribute: require('./view/text-attribute'),
      booleanAttribute: require('./view/boolean-attribute'),
      numberAttribute: require('./view/number-attribute'),
      enumAttribute: require('./view/enum-attribute'),
      enumAttributeList: require('./view/enum-attribute-list'),
      registerWith: function(library) {
        var _, ref, results, view;
        ref = this;
        results = [];
        for (_ in ref) {
          view = ref[_];
          if (view !== this.registerWith) {
            results.push(view.registerWith(library));
          }
        }
        return results;
      }
    }
  };

}).call(this);
