// Generated by CoffeeScript 1.6.2
(function() {
  var janus, kase, template, util, _base, _ref;

  util = require('./util/util');

  kase = require('./core/case');

  template = require('./view/template');

  janus = (_ref = (_base = typeof window !== "undefined" && window !== null ? window : global)._janus$) != null ? _ref : _base._janus$ = {
    util: util,
    Varying: require('./core/varying').Varying,
    defcase: kase.defcase,
    match: kase.match,
    otherwise: kase.otherwise,
    from: require('./core/from'),
    Library: require('./library/library').Library,
    Model: require('./model/model').Model,
    attribute: require('./model/attribute'),
    Issue: require('./model/issue').Issue,
    store: require('./model/store'),
    collection: require('./collection/collection'),
    View: require('./view/view').View,
    DomView: require('./view/dom-view').DomView,
    find: template.find,
    template: template.template,
    application: {
      App: require('./application/app').App,
      endpoint: require('./application/endpoint'),
      handler: require('./application/handler'),
      manifest: require('./application/manifest')
    }
  };

  util.extend(module.exports, janus);

}).call(this);
