// Generated by CoffeeScript 1.11.1
(function() {
  var ref, ref1;

  module.exports = typeof window === 'undefined' ? require('zepto-node')(require('domino').createWindow()) : (ref = (ref1 = window.jQuery) != null ? ref1 : window.Zepto) != null ? ref : window.$;

}).call(this);
