// Generated by CoffeeScript 1.12.2
(function() {
  var animationFrame, deferred, queuer, setMode, synchronous;

  animationFrame = function(f_) {
    var lastval, requested;
    requested = false;
    lastval = null;
    return function(x) {
      lastval = x;
      if (requested === false) {
        window.requestAnimationFrame((function(_this) {
          return function() {
            requested = false;
            f_.call(_this, lastval);
          };
        })(this));
        requested = true;
      }
    };
  };

  synchronous = function(f_) {
    return f_;
  };

  deferred = (function() {
    var flush, generation, queue, timer;
    timer = null;
    generation = 0;
    queue = [];
    flush = function() {
      var f_, flushQueue, i, len;
      timer = null;
      generation += 1;
      flushQueue = queue;
      queue = [];
      for (i = 0, len = flushQueue.length; i < len; i++) {
        f_ = flushQueue[i];
        f_();
      }
    };
    return function(f_) {
      var lastval, thisgen;
      thisgen = -1;
      lastval = null;
      return function(x) {
        lastval = x;
        if (thisgen < generation) {
          queue.push(function() {
            return f_.call(this, lastval);
          });
          thisgen = generation;
        }
        if (timer == null) {
          timer = setTimeout(flush, 0);
        }
      };
    };
  })();

  queuer = (typeof window !== "undefined" && window !== null ? window.requestAnimationFrame : void 0) != null ? animationFrame : synchronous;

  setMode = function(mode) {
    return queuer = mode;
  };

  module.exports = {
    queued: queuer
  };

}).call(this);
