// Generated by CoffeeScript 1.6.2
(function() {
  var defcase, extend, types;

  extend = require('./util').extend;

  defcase = require('../core/case').defcase;

  types = {
    result: defcase('org.janusjs.util.result', 'init', 'pending', 'progress', 'success', 'failure'),
    error: defcase('org.janusjs.util.error', 'denied', 'not_authorized', 'not_found', 'invalid', 'internal')
  };

  module.exports = types;

}).call(this);
