// Generated by CoffeeScript 1.6.2
(function() {
  var caseSet, extend, types;

  extend = require('./util').extend;

  caseSet = require('../core/case').caseSet;

  types = {
    result: caseSet('init', 'pending', 'progress', 'success', 'failure')
  };

  extend(module.exports, types);

}).call(this);
