// Generated by CoffeeScript 1.11.1
(function() {
  var List, Varying, isArray, ref, stringifier;

  ref = require('janus'), Varying = ref.Varying, List = ref.List;

  isArray = require('janus').util.isArray;

  stringifier = function(view) {
    if (view.options.stringify != null) {
      return Varying.of(view.options.stringify);
    } else if (view.subject.stringify != null) {
      return Varying.of(view.subject.stringify);
    } else {
      return new Varying(function(x) {
        var ref1;
        return (ref1 = x != null ? x.toString() : void 0) != null ? ref1 : '';
      });
    }
  };

  module.exports = {
    stringifier: stringifier
  };

}).call(this);
