// Generated by CoffeeScript 1.11.1
(function() {
  var List, Varying, asList, isArray, ref, stringifier;

  ref = require('janus'), Varying = ref.Varying, List = ref.List;

  isArray = require('janus').util.isArray;

  stringifier = function(view) {
    if (view.options.stringify != null) {
      return Varying.of(view.options.stringify);
    } else if (view.subject.stringify != null) {
      return Varying.of(view.subject.stringify);
    } else {
      return new Varying(function(x) {
        var ref1;
        return (ref1 = x != null ? x.toString() : void 0) != null ? ref1 : '';
      });
    }
  };

  asList = function(x) {
    if (x == null) {
      return new List();
    } else if (isArray(x)) {
      return new List(x);
    } else if (x.isMappable) {
      return x;
    } else {
      console.error('got an unexpected value for EnumAttribute#values', x);
      return new List();
    }
  };

  module.exports = {
    stringifier: stringifier,
    asList: asList
  };

}).call(this);
