// Generated by CoffeeScript 1.11.1
(function() {
  var Varying, stringifier;

  Varying = require('janus').Varying;

  stringifier = function(view) {
    if (view.options.stringify != null) {
      return Varying.ly(view.options.stringify);
    } else if (view.subject.stringify != null) {
      return Varying.ly(view.subject.stringify);
    } else {
      return new Varying(function(x) {
        return x != null ? x.toString() : void 0;
      });
    }
  };

  module.exports = {
    stringifier: stringifier
  };

}).call(this);
