// Generated by CoffeeScript 1.12.2
(function() {
  var Base, EventEmitter, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('eventemitter2').EventEmitter2;

  util = require('../util/util');

  Base = (function(superClass) {
    extend(Base, superClass);

    Base.prototype.isBase = true;

    function Base() {
      Base.__super__.constructor.call(this, {
        delimiter: ':',
        maxListeners: 0
      });
      this.setMaxListeners(0);
      this._outwardListeners = [];
      this._id = util.uniqueId();
      null;
    }

    Base.prototype.listenTo = function(target, event, handler) {
      this._outwardListeners.push(arguments);
      if (target != null) {
        if (typeof target.on === "function") {
          target.on(event, handler);
        }
      }
      return this;
    };

    Base.prototype.unlistenTo = function(tgt) {
      var event, handler, i, len, ref, ref1, target;
      ref = this._outwardListeners;
      for (i = 0, len = ref.length; i < len; i++) {
        ref1 = ref[i], target = ref1[0], event = ref1[1], handler = ref1[2];
        if (target === tgt) {
          if (target != null) {
            if (typeof target.off === "function") {
              target.off(event, handler);
            }
          }
        }
      }
      return this;
    };

    Base.prototype.destroy = function() {
      var event, handler, i, len, ref, ref1, target;
      this.emit('destroying');
      ref = this._outwardListeners;
      for (i = 0, len = ref.length; i < len; i++) {
        ref1 = ref[i], target = ref1[0], event = ref1[1], handler = ref1[2];
        if (target != null) {
          if (typeof target.off === "function") {
            target.off(event, handler);
          }
        }
      }
      return this.removeAllListeners();
    };

    Base.prototype.destroyWith = function(other) {
      return this.listenTo(other, 'destroying', (function(_this) {
        return function() {
          return _this.destroy();
        };
      })(this));
    };

    return Base;

  })(EventEmitter);

  module.exports = {
    Base: Base
  };

}).call(this);
