// Generated by CoffeeScript 1.12.2
(function() {
  var defcase, extend, types;

  extend = require('../util/util').extend;

  defcase = require('../core/case').defcase;

  types = {
    from: defcase('dynamic', 'watch', 'attribute', 'varying', 'app', 'self'),
    result: defcase('init', 'pending', 'progress', {
      'complete': ['success', 'failure']
    }),
    validity: defcase('valid', {
      'invalid': ['warning', 'error']
    }),
    operation: defcase('read', {
      'mutate': ['create', 'update', 'delete']
    }),
    traversal: defcase.withOptions({
      arity: 2
    })('recurse', 'delegate', 'defer', 'varying', 'value', 'nothing')
  };

  module.exports = types;

}).call(this);
