// Generated by CoffeeScript 1.12.2
(function() {
  var defcase, extend, types;

  extend = require('../util/util').extend;

  defcase = require('../core/case').defcase;

  types = {
    from: defcase('org.janusjs.core.from.default', 'dynamic', 'watch', 'attribute', 'varying', 'app', 'self'),
    result: defcase('org.janusjs.util.result', 'init', 'pending', 'progress', {
      'complete': ['success', 'failure']
    }),
    validity: defcase('org.janusjs.model.validity', 'valid', {
      'invalid': ['warning', 'error']
    }),
    operation: defcase('org.janusjs.reference.operation', 'read', {
      'mutate': ['create', 'update', 'delete']
    }),
    traversal: defcase({
      'org.janusjs.collection.traversal': {
        arity: 2
      }
    }, 'recurse', 'delegate', 'defer', 'varying', 'value', 'nothing')
  };

  module.exports = types;

}).call(this);
