// Generated by CoffeeScript 1.6.2
(function() {
  var ComposedVarying, FlatMappedVarying, FlattenedVarying, MappedVarying, Varied, Varying, fix, identity, isFunction, nothing, uniqueId, _ref,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('../util/util'), isFunction = _ref.isFunction, fix = _ref.fix, uniqueId = _ref.uniqueId;

  Varying = (function() {
    var _pure;

    Varying.prototype.isVarying = true;

    function Varying(value) {
      this.set(value);
      this._observers = {};
      this._generation = 0;
    }

    Varying.prototype.map = function(f) {
      return new MappedVarying(this, f);
    };

    Varying.prototype.flatten = function() {
      return new FlattenedVarying(this);
    };

    Varying.prototype.flatMap = function(f) {
      return new FlatMappedVarying(this, f);
    };

    Varying.prototype.react = function(f_) {
      var id,
        _this = this;

      id = uniqueId();
      return this._observers[id] = new Varied(id, f_, function() {
        return delete _this._observers[id];
      });
    };

    Varying.prototype.reactNow = function(f_) {
      var varied;

      varied = this.react(f_);
      f_.call(varied, this.get());
      return varied;
    };

    Varying.prototype.set = function(value) {
      var generation, observer, _, _ref1;

      if (value === this._value) {
        return;
      }
      generation = this._generation += 1;
      this._value = value;
      _ref1 = this._observers;
      for (_ in _ref1) {
        observer = _ref1[_];
        observer.f_(this._value);
        if (generation !== this._generation) {
          return;
        }
      }
      return null;
    };

    Varying.prototype.get = function() {
      return this._value;
    };

    _pure = function(flat) {
      return function() {
        var args, f;

        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (isFunction(args[0]) && (args[0].react == null)) {
          f = args[0];
          return (fix(function(curry) {
            return function(args) {
              if (args.length < f.length) {
                return function() {
                  var more;

                  more = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                  return curry(args.concat(more));
                };
              } else {
                return new ComposedVarying(args, f, flat);
              }
            };
          }))(args.slice(1));
        } else {
          f = args.pop();
          return new ComposedVarying(args, f, flat);
        }
      };
    };

    Varying.pure = _pure(false);

    Varying.mapAll = Varying.pure;

    Varying.flatMapAll = _pure(true);

    Varying.ly = function(x) {
      if ((x != null ? x.isVarying : void 0) === true) {
        return x;
      } else {
        return new Varying(x);
      }
    };

    return Varying;

  })();

  Varied = (function() {
    function Varied(id, f_, stop) {
      this.id = id;
      this.f_ = f_;
      this.stop = stop;
    }

    return Varied;

  })();

  identity = function(x) {
    return x;
  };

  nothing = {};

  FlatMappedVarying = (function(_super) {
    var _react;

    __extends(FlatMappedVarying, _super);

    function FlatMappedVarying(_parent, _f, _flatten) {
      this._parent = _parent;
      this._f = _f != null ? _f : identity;
      this._flatten = _flatten != null ? _flatten : true;
      this._observers = {};
      this._internalObservers = {};
      this._refCount = 0;
    }

    _react = function(self, callback, immediate) {
      var id, ignoreFirst, lastInnerVaried, lastValue, onValue, parentVaried, varied;

      id = uniqueId();
      self._observers[id] = varied = new Varied(id, callback, function() {
        delete self._observers[id];
        if (typeof lastInnerVaried !== "undefined" && lastInnerVaried !== null) {
          lastInnerVaried.stop();
        }
        return parentVaried.stop();
      });
      lastValue = nothing;
      lastInnerVaried = null;
      ignoreFirst = true;
      onValue = function(value) {
        if (value === lastValue) {
          return;
        }
        if (self._flatten === true && this === parentVaried) {
          if (lastInnerVaried != null) {
            lastInnerVaried.stop();
          }
          if ((value != null ? value.isVarying : void 0) === true) {
            lastInnerVaried = value.reactNow(onValue);
            return;
          } else {
            lastInnerVaried = null;
          }
        }
        if (!(immediate === false && ignoreFirst === true)) {
          callback.call(varied, value);
        }
        return lastValue = value;
      };
      parentVaried = self._bind(onValue);
      if (self._flatten === true || immediate === true) {
        onValue.call(parentVaried, self._immediate());
      }
      ignoreFirst = false;
      return varied;
    };

    FlatMappedVarying.prototype.react = function(f_) {
      return _react(this, f_, false);
    };

    FlatMappedVarying.prototype.reactNow = function(f_) {
      return _react(this, f_, true);
    };

    FlatMappedVarying.prototype._bind = function(callback) {
      var id, lastRaw, varied,
        _this = this;

      id = uniqueId();
      varied = new Varied(id, callback, function() {
        _this._refCount -= 1;
        delete _this._internalObservers[id];
        if (_this._refCount === 0) {
          return _this._parentVaried.stop();
        }
      });
      lastRaw = null;
      if (this._refCount === 0) {
        this._parentVaried = this._parent.reactNow(function(raw) {
          var mapped, o, _, _ref1, _results;

          if (raw === lastRaw) {
            return;
          }
          lastRaw = raw;
          mapped = _this._f.call(null, raw);
          _ref1 = _this._internalObservers;
          _results = [];
          for (_ in _ref1) {
            o = _ref1[_];
            _results.push(callback.call(o, mapped));
          }
          return _results;
        });
      }
      this._refCount += 1;
      return this._internalObservers[id] = varied;
    };

    FlatMappedVarying.prototype._immediate = function() {
      return this._f.call(null, this._parent.get());
    };

    FlatMappedVarying.prototype.set = null;

    FlatMappedVarying.prototype.get = function() {
      var result;

      result = this._immediate();
      if (this._flatten === true && (result != null ? result.isVarying : void 0) === true) {
        return result.get();
      } else {
        return result;
      }
    };

    return FlatMappedVarying;

  })(Varying);

  FlattenedVarying = (function(_super) {
    __extends(FlattenedVarying, _super);

    function FlattenedVarying(parent) {
      FlattenedVarying.__super__.constructor.call(this, parent);
    }

    return FlattenedVarying;

  })(FlatMappedVarying);

  MappedVarying = (function(_super) {
    __extends(MappedVarying, _super);

    function MappedVarying(parent, f) {
      MappedVarying.__super__.constructor.call(this, parent, f, false);
    }

    return MappedVarying;

  })(FlatMappedVarying);

  ComposedVarying = (function(_super) {
    __extends(ComposedVarying, _super);

    function ComposedVarying(_applicants, _f, _flatten) {
      this._applicants = _applicants;
      this._f = _f != null ? _f : identity;
      this._flatten = _flatten != null ? _flatten : false;
      this._observers = {};
      this._internalObservers = {};
      this._refCount = 0;
      this._partial = [];
      this._parentVarieds = [];
    }

    ComposedVarying.prototype._bind = function(callback) {
      var a, id, idx, varied,
        _this = this;

      id = uniqueId();
      varied = new Varied(id, callback, function() {
        var v, _i, _len, _ref1, _results;

        _this._refCount -= 1;
        delete _this._internalObservers[id];
        if (_this._refCount === 0) {
          _ref1 = _this._parentVarieds;
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            v = _ref1[_i];
            _results.push(v.stop());
          }
          return _results;
        }
      });
      if (this._refCount === 0) {
        this._parentVarieds = (function() {
          var _i, _len, _ref1, _results,
            _this = this;

          _ref1 = this._applicants;
          _results = [];
          for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
            a = _ref1[idx];
            _results.push((function(a, idx) {
              return a.reactNow(function(value) {
                var o, _, _ref2, _results1;

                _this._partial[idx] = value;
                _ref2 = _this._internalObservers;
                _results1 = [];
                for (_ in _ref2) {
                  o = _ref2[_];
                  _results1.push(o.f_(_this._f.apply(_this._parentVarieds[idx], _this._partial)));
                }
                return _results1;
              });
            })(a, idx));
          }
          return _results;
        }).call(this);
      }
      this._refCount += 1;
      return this._internalObservers[id] = varied;
    };

    ComposedVarying.prototype._immediate = function() {
      var a;

      return this._f.apply(null, (function() {
        var _i, _len, _ref1, _results;

        _ref1 = this._applicants;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          a = _ref1[_i];
          _results.push(a.get());
        }
        return _results;
      }).call(this));
    };

    return ComposedVarying;

  })(FlatMappedVarying);

  module.exports = {
    Varying: Varying,
    Varied: Varied,
    FlatMappedVarying: FlatMappedVarying,
    FlattenedVarying: FlattenedVarying,
    MappedVarying: MappedVarying,
    ComposedVarying: ComposedVarying
  };

}).call(this);
