// Generated by CoffeeScript 1.6.2
(function() {
  var DerivedList, FlattenedList, List, util, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./list'), List = _ref.List, DerivedList = _ref.DerivedList;

  util = require('../util/util');

  FlattenedList = (function(_super) {
    var sizeof;

    __extends(FlattenedList, _super);

    function FlattenedList(parent, options) {
      var idx, list, _i, _len, _ref1,
        _this = this;

      this.parent = parent;
      this.options = options != null ? options : {};
      FlattenedList.__super__.constructor.call(this);
      this._listListeners = new List();
      _ref1 = this.parent.list;
      for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
        list = _ref1[idx];
        this._addObj(list, idx);
      }
      this.parent.on('added', function(obj, idx) {
        return _this._addObj(obj, idx);
      });
      this.parent.on('moved', function(obj, idx, oldIdx) {
        return _this._moveObj(obj, oldIdx, idx);
      });
      this.parent.on('removed', function(obj, idx) {
        return _this._removeObj(obj, idx);
      });
    }

    sizeof = function(x) {
      if ((x != null ? x.isCollection : void 0) === true) {
        return x.length;
      } else {
        return 1;
      }
    };

    FlattenedList.prototype._getOverallIdx = function(parentIdx, offset) {
      if (offset == null) {
        offset = 0;
      }
      return util.foldLeft(0)(this.parent.list.slice(0, parentIdx), function(length, x) {
        return length + sizeof(x);
      }) + offset;
    };

    FlattenedList.prototype._addObj = function(obj, idx) {
      var elem, event, handler, listeners, offset, _i, _len, _ref1, _results,
        _this = this;

      if ((obj != null ? obj.isCollection : void 0) === true) {
        listeners = {
          added: function(elem, offset) {
            return _this._add(elem, _this._getOverallIdx(_this._listListeners.list.indexOf(listeners), offset));
          },
          moved: function(elem, newIdx, oldIdx) {
            var mappedBase;

            mappedBase = _this._getOverallIdx(_this._listListeners.list.indexOf(listeners));
            return _this._moveAt(mappedBase + oldIdx, mappedBase + newIdx);
          },
          removed: function(_, offset) {
            return _this._removeAt(_this._getOverallIdx(_this._listListeners.list.indexOf(listeners), offset));
          }
        };
        for (event in listeners) {
          handler = listeners[event];
          obj.on(event, handler);
        }
        this._listListeners.add(listeners, idx);
        _ref1 = obj.list;
        _results = [];
        for (offset = _i = 0, _len = _ref1.length; _i < _len; offset = ++_i) {
          elem = _ref1[offset];
          _results.push(this._add(elem, this._getOverallIdx(idx, offset)));
        }
        return _results;
      } else {
        return this._add(obj, this._getOverallIdx(idx));
      }
    };

    FlattenedList.prototype._moveObj = function(obj, oldIdx, newIdx) {
      var mNewIdx, mOldIdx, offset, _, _i, _j, _ref1, _ref2;

      mOldIdx = this._getOverallIdx(oldIdx);
      mNewIdx = this._getOverallIdx(newIdx);
      if ((obj != null ? obj.isCollection : void 0) === true) {
        if (newIdx > oldIdx) {
          mNewIdx += sizeof(obj);
          mNewIdx -= sizeof(this.parent.list[newIdx - 1]);
        }
        if (newIdx < oldIdx) {
          mOldIdx -= sizeof(obj);
          mOldIdx += sizeof(this.parent.list[oldIdx]);
        }
        if (newIdx > oldIdx) {
          for (_ = _i = 0, _ref1 = obj.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; _ = 0 <= _ref1 ? ++_i : --_i) {
            this._moveAt(mOldIdx, mNewIdx);
          }
        } else if (newIdx < oldIdx) {
          for (offset = _j = 0, _ref2 = obj.length; 0 <= _ref2 ? _j < _ref2 : _j > _ref2; offset = 0 <= _ref2 ? ++_j : --_j) {
            this._moveAt(mOldIdx + offset, mNewIdx + offset);
          }
        }
      } else {
        this._moveAt(mOldIdx, mNewIdx);
      }
      return this._listListeners.moveAt(oldIdx, newIdx);
    };

    FlattenedList.prototype._removeObj = function(obj, idx) {
      var event, handler, listeners, objStartIdx, _, _i, _len, _ref1;

      objStartIdx = this._getOverallIdx(idx);
      listeners = this._listListeners.removeAt(idx);
      if ((obj != null ? obj.isCollection : void 0) === true) {
        for (event in listeners) {
          handler = listeners[event];
          obj.off(event, handler);
        }
        _ref1 = obj.list;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          _ = _ref1[_i];
          this._removeAt(objStartIdx);
        }
      } else {
        this._removeAt(objStartIdx);
      }
      return null;
    };

    FlattenedList.prototype.destroy = function() {
      var event, handler, idx, listeners, _i, _len, _ref1;

      _ref1 = this._listListeners.list;
      for (idx = _i = 0, _len = _ref1.length; _i < _len; idx = ++_i) {
        listeners = _ref1[idx];
        if (listeners != null) {
          for (event in listeners) {
            handler = listeners[event];
            this.parent.list[idx].off(event, handler);
          }
        }
      }
      return FlattenedList.__super__.destroy.call(this);
    };

    return FlattenedList;

  })(DerivedList);

  module.exports = {
    FlattenedList: FlattenedList
  };

}).call(this);
