// Generated by CoffeeScript 1.12.2
(function() {
  var Varying, foldBase, folds;

  Varying = require('../core/varying').Varying;

  foldBase = function(update) {
    return function(collection) {
      var result, watched;
      result = new Varying(null);
      watched = 0;
      collection.length.react(function(length) {
        var fn, i, idx, ref, ref1;
        fn = function(idx) {
          return collection.at(idx).react(function(value) {
            return result.set(update(value, idx, collection));
          });
        };
        for (idx = i = ref = watched, ref1 = length; ref <= ref1 ? i < ref1 : i > ref1; idx = ref <= ref1 ? ++i : --i) {
          fn(idx);
        }
        return watched = length;
      });
      return result;
    };
  };

  folds = {
    apply: function(collection, f) {
      return collection.length.flatMap(function(length) {
        var idx;
        return Varying.all((function() {
          var i, ref, results;
          results = [];
          for (idx = i = 0, ref = collection.length_; 0 <= ref ? i <= ref : i >= ref; idx = 0 <= ref ? ++i : --i) {
            results.push(collection.at(idx));
          }
          return results;
        })()).map(f);
      });
    },
    join: function(collection, joiner) {
      return foldBase(function(_, _2, collection) {
        return collection.list.join(joiner);
      })(collection);
    },
    scanl: function(collection, memo, f) {
      var result, self;
      self = new Varying();
      result = collection.enumerate().flatMap(function(idx) {
        return self.flatMap(function(result) {
          var prev;
          if (result == null) {
            return;
          }
          prev = idx === 0 ? Varying.of(memo) : result.at(idx - 1);
          return Varying.mapAll(f, prev, collection.at(idx));
        });
      });
      self.set(result);
      return result;
    },
    foldl: function(collection, memo, f) {
      return folds.scanl(collection, memo, f).at(-1);
    }
  };

  module.exports = folds;

}).call(this);
