// Generated by CoffeeScript 1.12.2
(function() {
  var DerivedList, List, OrderedCollection, Varying, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Varying = require('../core/varying').Varying;

  OrderedCollection = require('./collection').OrderedCollection;

  util = require('../util/util');

  List = (function(superClass) {
    var _at, _watchAt;

    extend(List, superClass);

    List.prototype.isList = true;

    function List(list, options) {
      if (list == null) {
        list = [];
      }
      if ((options != null ? options.parent : void 0) != null) {
        this._parent = options.parent;
      }
      List.__super__.constructor.call(this, {}, options);
      if (typeof this._initialize === "function") {
        this._initialize();
      }
      this.list = [];
      this.add(list);
    }

    List.prototype.add = function(elems, idx) {
      var elem, j, len, subidx;
      if (idx == null) {
        idx = this.list.length;
      }
      if (!util.isArray(elems)) {
        elems = [elems];
      }
      if (idx === this.list.length && elems.length === 1) {
        this.list.push(elems[0]);
      } else {
        if (idx > this.list.length) {
          this.list[idx - 1] = null;
          delete this.list[idx - 1];
        }
        Array.prototype.splice.apply(this.list, [idx, 0].concat(elems));
      }
      for (subidx = j = 0, len = elems.length; j < len; subidx = ++j) {
        elem = elems[subidx];
        this.emit('added', elem, idx + subidx);
        if (elem != null) {
          if (typeof elem.emit === "function") {
            elem.emit('addedTo', this, idx + subidx);
          }
        }
        if ((elem != null ? elem.isBase : void 0) === true) {
          (function(_this) {
            return (function(elem) {
              return _this.listenTo(elem, 'destroying', function() {
                return _this.remove(elem);
              });
            });
          })(this)(elem);
        }
      }
      return elems;
    };

    List.prototype.remove = function(which) {
      var idx;
      idx = this.list.indexOf(which);
      if (!(idx >= 0)) {
        return void 0;
      }
      return this.removeAt(idx);
    };

    List.prototype.removeAt = function(idx) {
      var removed;
      if (idx < 0) {
        idx = this.list.length + idx;
      }
      if (idx < 0 || idx >= this.list.length) {
        return;
      }
      removed = idx === 0 ? this.list.shift() : idx === this.list.length - 1 ? this.list.pop() : this.list.splice(idx, 1)[0];
      this.emit('removed', removed, idx);
      if (removed != null) {
        if (typeof removed.emit === "function") {
          removed.emit('removedFrom', this, idx);
        }
      }
      return removed;
    };

    List.prototype.move = function(elem, idx) {
      var oldIdx;
      oldIdx = this.list.indexOf(elem);
      if (!(oldIdx >= 0)) {
        return;
      }
      return this.moveAt(oldIdx, idx);
    };

    List.prototype.moveAt = function(oldIdx, idx) {
      var elem;
      elem = this.list[oldIdx];
      this.list.splice(oldIdx, 1);
      this.list.splice(idx, 0, elem);
      this.emit('moved', elem, idx, oldIdx);
      if (elem != null) {
        if (typeof elem.emit === "function") {
          elem.emit('movedIn', this, idx, oldIdx);
        }
      }
      return elem;
    };

    List.prototype.removeAll = function() {
      var elem, results;
      results = [];
      while (this.list.length > 0) {
        elem = this.list.shift();
        this.emit('removed', elem, 0);
        if (elem != null) {
          if (typeof elem.emit === "function") {
            elem.emit('removedFrom', this, 0);
          }
        }
        results.push(elem);
      }
      return results;
    };

    _at = function(idx) {
      if (idx >= 0) {
        return this.list[idx];
      } else {
        return this.list[this.list.length + idx];
      }
    };

    List.prototype.at = _at;

    List.prototype.get = _at;

    _watchAt = function(idx) {
      var result;
      if ((idx != null ? idx.isVarying : void 0) === true) {
        return idx.flatMap((function(_this) {
          return function(tidx) {
            return _this.watchAt(tidx);
          };
        })(this));
      }
      result = new Varying(this.at(idx));
      this.on('added', (function(_this) {
        return function(elem, midx) {
          if (idx === midx) {
            return result.set(elem);
          } else if ((idx > 0) && (midx < idx)) {
            return result.set(_this.at(idx));
          } else if ((idx < 0) && (midx >= (_this.list.length + idx))) {
            return result.set(_this.at(idx));
          }
        };
      })(this));
      this.on('moved', (function(_this) {
        return function(elem, newIdx, oldIdx) {
          var tidx;
          tidx = idx < 0 ? _this.list.length + idx : idx;
          if (tidx === newIdx) {
            return result.set(elem);
          } else if (tidx === oldIdx) {
            return result.set(_this.at(tidx));
          } else if (tidx > oldIdx && tidx < newIdx) {
            return result.set(_this.at(tidx));
          } else if (tidx < oldIdx && tidx > newIdx) {
            return result.set(_this.at(tidx));
          }
        };
      })(this));
      this.on('removed', (function(_this) {
        return function(_, midx) {
          if ((idx >= 0) && (midx <= idx)) {
            return result.set(_this.at(idx));
          } else if ((idx < 0) && (midx >= (_this.list.length + idx))) {
            return result.set(_this.at(idx));
          }
        };
      })(this));
      return result;
    };

    List.prototype.watchAt = _watchAt;

    List.prototype.watch = _watchAt;

    Object.defineProperty(List.prototype, 'length', {
      get: function() {
        return this.list.length;
      }
    });

    List.prototype.watchLength = function() {
      var result;
      result = new Varying(this.list.length);
      this.on('added', function() {
        return result.set(this.list.length);
      });
      this.on('removed', function() {
        return result.set(this.list.length);
      });
      return result;
    };

    List.prototype.put = function(list, idx) {
      var elem, j, k, len, len1, ref, removed, subidx;
      if (!util.isArray(list)) {
        list = [list];
      }
      if (idx > this.list.length) {
        this.list[idx] = null;
        delete this.list[idx];
      }
      removed = (ref = this.list).splice.apply(ref, [idx, list.length].concat(slice.call(list)));
      for (subidx = j = 0, len = removed.length; j < len; subidx = ++j) {
        elem = removed[subidx];
        this.emit('removed', elem, idx + subidx);
        if (elem != null) {
          if (typeof elem.emit === "function") {
            elem.emit('removedFrom', this, idx + subidx);
          }
        }
      }
      for (subidx = k = 0, len1 = list.length; k < len1; subidx = ++k) {
        elem = list[subidx];
        this.emit('added', elem, idx + subidx);
        if (elem != null) {
          if (typeof elem.emit === "function") {
            elem.emit('addedTo', this, idx + subidx);
          }
        }
      }
      return removed;
    };

    List.prototype.set = function(idx, item) {
      return this.put([item], idx);
    };

    List.prototype.putAll = function(list) {
      var elem, i, j, k, len, len1, oldIdx, ref;
      ref = this.list.slice();
      for (j = 0, len = ref.length; j < len; j++) {
        elem = ref[j];
        if (!(list.indexOf(elem) >= 0)) {
          this.remove(elem);
        }
      }
      for (i = k = 0, len1 = list.length; k < len1; i = ++k) {
        elem = list[i];
        if (this.list[i] === elem) {
          continue;
        }
        oldIdx = this.list.indexOf(elem);
        if (oldIdx >= 0) {
          this.move(elem, i);
        } else {
          this.add(elem, i);
        }
      }
      return list;
    };

    List.prototype.shadow = function() {
      var item, newArray;
      newArray = (function() {
        var j, len, ref, results;
        ref = this.list;
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          item = ref[j];
          if ((item != null ? item.isEnumerable : void 0) === true) {
            results.push(item.shadow());
          } else {
            results.push(item);
          }
        }
        return results;
      }).call(this);
      return new this.constructor(newArray, {
        parent: this
      });
    };

    List.deserialize = function(data) {
      var datum, items;
      items = (function() {
        var j, len, results;
        if ((this.modelClass != null) && util.isFunction(this.modelClass.deserialize)) {
          results = [];
          for (j = 0, len = data.length; j < len; j++) {
            datum = data[j];
            results.push(this.modelClass.deserialize(datum));
          }
          return results;
        } else {
          return data.slice();
        }
      }).call(this);
      return new this(items);
    };

    List.of = function(modelClass) {
      return (function(superClass1) {
        extend(_Class, superClass1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        _Class.modelClass = modelClass;

        return _Class;

      })(this);
    };

    return List;

  })(OrderedCollection);

  DerivedList = (function(superClass) {
    var j, len, method, ref, roError;

    extend(DerivedList, superClass);

    function DerivedList() {
      OrderedCollection.call(this);
      this.list = [];
      if (typeof this._initialize === "function") {
        this._initialize();
      }
    }

    roError = function() {
      throw new Error('this list is read-only');
    };

    ref = ['add', 'remove', 'removeAt', 'removeAll', 'put', 'putAll', 'move', 'moveAt'];
    for (j = 0, len = ref.length; j < len; j++) {
      method = ref[j];
      DerivedList.prototype["_" + method] = DerivedList.__super__[method];
      DerivedList.prototype[method] = roError;
    }

    DerivedList.prototype.shadow = function() {
      return this;
    };

    return DerivedList;

  })(List);

  module.exports = {
    List: List,
    DerivedList: DerivedList
  };

}).call(this);
