// Generated by CoffeeScript 1.12.2
(function() {
  var List, Mappable, Set, Varying, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Varying = require('../core/varying').Varying;

  Mappable = require('./collection').Mappable;

  List = require('./list').List;

  util = require('../util/util');

  Set = (function(superClass) {
    extend(Set, superClass);

    function Set(init) {
      this._watched = [];
      this._watchers = [];
      this._list = new List();
      this.list = this._list.list;
      this.add(init);
    }

    Set.prototype.add = function(elems) {
      var elem, i, len, widx;
      if (!util.isArray(elems)) {
        elems = [elems];
      }
      for (i = 0, len = elems.length; i < len; i++) {
        elem = elems[i];
        if (!(!this.has(elem))) {
          continue;
        }
        widx = this._watched.indexOf(elem);
        if (widx >= 0) {
          this._watchers[widx].set(true);
        }
        this._list.add(elem);
        this.emit('added', elem);
      }
      return elems;
    };

    Set.prototype.remove = function(elem) {
      var idx, widx;
      widx = this._watched.indexOf(elem);
      if (widx >= 0) {
        this._watchers[widx].set(false);
      }
      idx = this.list.indexOf(elem);
      if (!(idx >= 0)) {
        return void 0;
      }
      this._list.removeAt(idx);
      this.emit('removed', elem);
      return null;
    };

    Set.prototype.putAll = function(elems) {
      var i, len, ref, x;
      ref = this.list.slice();
      for (i = 0, len = ref.length; i < len; i++) {
        x = ref[i];
        if (elems.indexOf(x) < 0) {
          this.remove(x);
        }
      }
      return this.add(elems);
    };

    Set.prototype.has = function(elem) {
      return this.list.indexOf(elem) >= 0;
    };

    Set.prototype.watchHas = function(elem) {
      var v;
      v = new Varying(this.has(elem));
      this._watched.push(elem);
      this._watchers.push(v);
      return v;
    };

    Object.defineProperty(Set.prototype, 'length', {
      get: function() {
        return this.list.length;
      }
    });

    Set.prototype.flatten = function() {
      return new (require('./derived/flattened-set').FlattenedSet)(this);
    };

    Set.prototype.enumerate = function() {
      return this.list.slice();
    };

    Set.prototype.enumeration = function() {
      return this;
    };

    Set.prototype.filter = function(f) {
      return this._list.filter(f);
    };

    Set.prototype.map = function(f) {
      return this._list.map(f);
    };

    Set.prototype.flatMap = function(f) {
      return this._list.flatMap(f);
    };

    Set.prototype.uniq = function() {
      return this;
    };

    Set.prototype.any = function(f) {
      return this._list.any(f);
    };

    return Set;

  })(Mappable);

  module.exports = {
    Set: Set
  };

}).call(this);
